# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 02:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.DurationField(default=datetime.timedelta(30))),
                ('memory_limit', models.BigIntegerField(default=134217728)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed Successfully'), ('W', 'Waiting to be Scheduled'), ('F', 'Failed to Schedule'), ('E', 'Completed with Errors')], default='W', max_length=1)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ui.models.user_directory_path)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(default='E', max_length=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='executable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executables', to='ui.UserFiles'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='input_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='ui.UserFiles'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Node'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='output_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='ui.UserFiles'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
