# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed Successfully'), ('W', 'Waiting to be Scheduled'), ('F', 'Failed to Schedule'), ('E', 'Completed with Errors'), ('T', 'Time Limit Exceeded')], default='W', max_length=1),
        ),
    ]
