# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4')),
                ('port', models.IntegerField(default=80)),
                ('state', models.CharField(choices=[('HL', 'Healthy Leader'), ('C', 'Candidate'), ('HS', 'Healthy Single'), ('HF', 'Healthy Follower'), ('FF', 'Failed Follower'), ('FL', 'Failed Leader'), ('RF', 'Requested to Follow')], default='HS', max_length=2)),
                ('host', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_used_percent', models.FloatField(default=0.0)),
                ('memory_available', models.BigIntegerField(default=0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('cpu_total', models.IntegerField(default=1)),
                ('cpu_used_percent', models.FloatField(default=0.0)),
                ('cpu_idle_percent', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('ip', 'port')]),
        ),
    ]
