# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executable_file', models.FileField(upload_to=scheduler.models.exec_directory_path)),
                ('input_file', models.FileField(upload_to=scheduler.models.exec_directory_path)),
                ('output_file', models.FileField(upload_to=scheduler.models.exec_directory_path)),
                ('time_limit', models.DurationField(default=datetime.timedelta(30))),
                ('memory_limit', models.BigIntegerField(default=134217728)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.DurationField(default=datetime.timedelta(30))),
                ('memory_limit', models.BigIntegerField(default=134217728)),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executables', to='ui.UserFiles')),
                ('input_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='ui.UserFiles')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Node')),
                ('output_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='ui.UserFiles')),
            ],
        ),
    ]
