# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_execution_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('F', 'Failed'), ('R', 'Running'), ('S', 'Success')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('D', 'Done')], default='R', max_length=1),
        ),
    ]
